@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Oct 28 13:02:59 +0100 2020
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim tb_cnt_behav -key {Behavioral:sim_1:Functional:tb_cnt} -tclbatch tb_cnt.tcl -view C:/Users/gabri/OneDrive/Desktop/Vivado Projects/Labs/05/DecimalCounter/tb_cnt_behav.wcfg -log simulate.log"
call xsim  tb_cnt_behav -key {Behavioral:sim_1:Functional:tb_cnt} -tclbatch tb_cnt.tcl -view C:/Users/gabri/OneDrive/Desktop/Vivado Projects/Labs/05/DecimalCounter/tb_cnt_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
