webtalk_init -webtalk_dir C:/Users/gabri/OneDrive/Desktop/Vivado Projects/Assignment/matrix_dot_product/matrix_dot_product.sim/sim_2/behav/xsim/xsim.dir/matrix_dot_mul_tb_enh_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Dec 15 13:05:24 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "eeb69248-5f4c-4ea3-8706-7bcc79ea878a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c7548f8e474f455e94efec1eff57a7a6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "47" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2304 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "11" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "89 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "17 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "216" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "106" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.56_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "70116_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2127443946 -regid "" -xml C:/Users/gabri/OneDrive/Desktop/Vivado Projects/Assignment/matrix_dot_product/matrix_dot_product.sim/sim_2/behav/xsim/xsim.dir/matrix_dot_mul_tb_enh_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/gabri/OneDrive/Desktop/Vivado Projects/Assignment/matrix_dot_product/matrix_dot_product.sim/sim_2/behav/xsim/xsim.dir/matrix_dot_mul_tb_enh_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/gabri/OneDrive/Desktop/Vivado Projects/Assignment/matrix_dot_product/matrix_dot_product.sim/sim_2/behav/xsim/xsim.dir/matrix_dot_mul_tb_enh_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
